Repository projeto-siga/siga, pull requests merged in 2020-08, with the labels that each got.

#1478 GOVSP1427* - Validações nos campos Freemarker
  siga-ex/src/main/resources/br/gov/jfrj/siga/ex/util/default.ftl
  siga/src/main/webapp/WEB-INF/page/login/login.jsp
  siga/src/main/webapp/css/style_siga.css
  siga/src/main/webapp/javascript/siga.js
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/edita.jsp
  sigaex/src/main/webapp/javascript/documento.validacao.js
  sigaex/src/main/webapp/javascript/exDocumentoEdita.js
Labels: enhancement, refactoring

#1303 815#Mensagem desentranhar quando solicitar cancelamento de doc juntado
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExDocumentoVO.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExMobilVO.java
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/exibe.jsp
  sigaex/src/main/webapp/WEB-INF/tags/mensagem/alerta-modal.tag
Labels: blocked

#1509 GOVSP1454 - Mensagens validação para ação de Ciência
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/AbstractExMovimentacao.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aCiencia.jsp
Labels: enhancement

#1510 Ordenação das opções de Marcadores de documento.
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/AbstractCpMarcador.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/CpMarcador.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V83_0__Marcadores_ordem.sql
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
Labels: database

#1513 GOVSP685 - Recebimento automático de documento via parâmetro
  siga/src/main/webapp/css/style_siga.css
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/ExApiV1Servlet.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExDocumentoController.java
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/edita.jsp
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/exibe.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/anexarArquivoAuxiliar.jsp
  sigaex/src/main/webapp/WEB-INF/tags/mensagem/alerta-modal.tag
Labels: enhancement, system-properties

#1516 GOVSP1471-Alteração tipo de espécie bloqueado quando espécie vinculada a documentos
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/ExFormaDocumento.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExFormaDocumentoController.java
Labels: bug

#1418 Permissão para alteração de lotação com documentos - issue #1416
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/AbstractDpLotacao.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/dao/CpDao.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V85_Permissao_alterar_lotacao_com_documentos.sql
  siga/src/main/java/br/gov/jfrj/siga/vraptor/DpLotacaoController.java
Labels: database
