Repository projeto-siga/siga, pull requests merged in 2020-07, with the labels that each got.

#1352 TRF2 - Permitindo que qualquer cosignatário possa assinar primeiro desde que tenha configuração pode Cosignatário assinar primeiro cadastrada.
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpTipoConfiguracao.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExCompetenciaBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExMarcadorBL.java
Labels: database

#1357 TRF2 - Criar nova configuração para permitir não finalizar o capturado e configuração para trocar o pdf do capturado.
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpTipoConfiguracao.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V69_0__Criar_tipo_configuracao_cosignatario_pode_assinar_primeiro.sql
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V70_0__Criar_tipo_configuracao_finalizar_automaticamente_capturados - Copia.sql
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V71_0__Criar_tipo_configuracao_trocar_pdf_capturados.sql
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExDocumentoController.java
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/edita.jsp
Labels: database

#1361 GOVSP1126* - Mesa 2 - Mostrar TMP somente na pasta Em Elaboração
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpTipoConfiguracao.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V69_0__Configuracao Mostrar Temporario na Lotacao.sql
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExMarcadorBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2.java
  siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
Labels: database

#1373 1285* - Publicação, Visualização e Integração de Processos no Portal da Transparência
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/AbstractCpToken.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpToken.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpBL.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/util/SigaUtil.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/CpMarcador.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/CpTipoMarcador.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/dao/CpDao.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V73_0__Estrutura_Publicacao_Portal_Transparencia.sql
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V73_1__adequacao-marcas-portal-transparencia.sql
  siga-cp/src/main/resources/messages_GOVSP.properties
  siga-cp/src/main/resources/messages_SIGA.properties
  siga-cp/src/main/resources/messages_TRF2.properties
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/ExTipoMovimentacao.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExCompetenciaBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExMarcadorBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExDocumentoVO.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExMobilVO.java
  siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
  siga-ex/src/main/resources/META-INF/persistence.xml
  siga-ex/src/main/resources/db/migration/SIGA_UTF8_V88__insert-tipo-mov-portal-transparencia.sql
  siga-ws/src/main/java/br/gov/jfrj/siga/ex/service/ExService.java
  siga/src/main/java/br/gov/jfrj/siga/unirest/proxy/GoogleRecaptcha.java
  siga/src/main/java/br/gov/jfrj/siga/vraptor/SigaLinkPermanenteController.java
  siga/src/main/webapp/META-INF/persistence.xml
  siga/src/main/webapp/WEB-INF/page/sigaLinkPermanente/publicPermanenteURL.jsp
  siga/src/main/webapp/WEB-INF/page/sigaLinkPermanente/publicPermanenteURLPdfView.jsp
  sigaex/src/main/java/br/gov/jfrj/siga/ex/service/impl/ExServiceImpl.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExArquivoController.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExSelecionavelController.java
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aPublicarTransparencia.jsp
Labels: database, system-properties

#1378 GOVSP - Conflitos de Scripts Migração EAP7
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V44_0__orgao_cinco.sql
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V48_0__incluindo_id_localidade.sql
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V48_0__update Tipo Doc Incluir Documento.sql
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V63_1__Acerto de Rollback.sql
  siga-ex/src/main/resources/db/migration/SIGA_UTF8_V50_0__Description.sql
Labels: database

#1383 GOVSP1308 Configuração para acesso somente ao recebedor e marcas da lotação conforme permissão de acesso
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpTipoConfiguracao.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V73_Configuracao_restringir_acesso_recebedor.sql
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/AcessoConsulta.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExAcesso.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExMarcadorBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExDocumentoVO.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aPublicarTransparencia.jsp
Labels: database, enhancement

#1391 TRF2 - Compatibilizar timestamp criado na tabela EX_MOVIMENTACAO para manter compatibilidade com mysql
  siga-ex/src/main/resources/db/migration/SIGA_UTF8_V88__AlterTable_dt_movimentacao_compat_mysql.sql
Labels: compat-mysql-oracle, database

#1395 GOVSP1285* - Ajustes complementares e adequação método getDocumento
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpTipoConfiguracao.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpCompetenciaBL.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/util/SigaUtil.java
  siga-cp/src/main/java/br/gov/jfrj/siga/gi/service/impl/GiServiceImpl.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V74_0__Configuracao_autorizacao_movimentacao_via_ws.sql
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExCompetenciaBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
  siga-ws/src/main/java/br/gov/jfrj/siga/ex/service/ExService.java
  siga/src/main/java/br/gov/jfrj/siga/vraptor/SigaLinkPermanenteController.java
  siga/src/main/webapp/WEB-INF/page/sigaLinkPermanente/publicPermanenteURLPdfView.jsp
  sigaex/src/main/java/br/gov/jfrj/siga/ex/service/impl/ExServiceImpl.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExArquivoController.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
Labels: database

#1405 Criação de Parâmetro para Numeração de Expediente
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
Labels: system-properties

#1420 Ajuste na PARAMETRIZAÇÃO do valor do botão do Login SSO
  siga-oidc/pom.xml
  siga-oidc/src/main/java/br/gov/sp/prodesp/siga/servlet/CallBackServlet.java
  siga-vraptor-module/src/main/java/br/gov/jfrj/siga/idp/jwt/AuthJwtFormFilter.java
  siga/src/main/java/br/gov/jfrj/siga/vraptor/LoginController.java
  siga/src/main/webapp/WEB-INF/page/login/login.jsp
Labels: enhancement, system-properties

#1437 GOVSP1085* - Não mostrar documento tramitado na pasta Aguardando Andamento da Mesa Virtual 2
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/AbstractCpMarcador.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V74_0__grupos de marcadores.sql
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2.java
  siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
Labels: bug, database
