Repository projeto-siga/siga, pull requests merged in 2021-09, with the labels that each got.

#1958 PDF de documentos sigilosos sendo disponibilizados na consulta pública
  sigaex/src/main/webapp/WEB-INF/page/exProcessoConsultaPublica/processoPublicoConsultado.jsp
Labels: bug

#1959 Parametrização do texto exibido ao usuário ao tentar cancelar um documento.
  siga-cp/src/main/resources/messages_GOVSP.properties
  siga-cp/src/main/resources/messages_PCRJ.properties
  siga-cp/src/main/resources/messages_SIGA.properties
  siga-cp/src/main/resources/messages_TRF2.properties
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga/src/main/java/br/gov/jfrj/siga/vraptor/LoginController.java
  sigaex/src/main/webapp/imagens/imgBrasao@2x.png
Labels: system-properties

#1969 GOVSP58859 - Alteração de nomenclatura pessoa/usuário e lotação/unidade nos marcadores
  siga-base/src/main/java/br/gov/jfrj/siga/base/Prop.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpBL.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/model/enm/CpMarcadorFinalidadeEnum.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/model/enm/CpMarcadorTipoInteressadoEnum.java
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/marcar.jsp
Labels: system-properties, OnlyGOVSP
