Repository projeto-siga/siga, pull requests merged in 2021-06, with the labels that each got.

#1868 66164* - Exibir conteúdo no acompanhamento de protoc. do doc filho
  siga-base/src/main/java/br/gov/jfrj/siga/base/Prop.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/ExMobil.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExCompetenciaBL.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/DocumentosSiglaHtmlGet.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/ExApiV1Servlet.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExProcessoAutenticacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exProcessoAutenticacao/processoArquivoAutenticado.jsp
Labels: system-properties

#1877 FIX: Correção de Queries com Select Max por ID
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/AbstractDpCargo.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/AbstractDpFuncaoConfianca.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/AbstractDpLotacao.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/AbstractDpPessoa.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/dao/CpDao.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V107_0__create_idx_email_dppessoa.sql
  siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
  siga-ex/src/main/resources/db/migration/SIGA_UTF8_V98_0__index_exmov_dttimestamp.sql
Labels: database

#1882 66472* Permitir pesquisa por modelos proibidos na tela "Criar Novo"
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
Labels: bug
