Repository projeto-siga/siga, pull requests merged in 2021-07, with the labels that each got.

#1889 PCRJ_647 - Protocolo de atendimento - brasao e Messages_properties PCRJ
  siga-cp/src/main/resources/messages_PCRJ.properties
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/gerarProtocolo.jsp
  sigaex/src/main/webapp/imagens/BrasaoPCRJ.png
Labels: system-properties

#1901 PCRJ_788 Mensagem "Not Found" aparecendo no canto inferior direito na tela de exibição do documento
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/exibe.jsp
Labels: bug

#1905 PCRJ_455 Consulta pública de documento
  siga-cp/src/main/resources/messages_GOVSP.properties
  siga-cp/src/main/resources/messages_PCRJ.properties
  siga-cp/src/main/resources/messages_SIGA.properties
  siga-cp/src/main/resources/messages_TRF2.properties
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExMovimentacaoVO.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/ExApiV1Servlet.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExArquivoController.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExProcessoConsultaPublicaController.java
  sigaex/src/main/webapp/WEB-INF/page/exProcessoConsultaPublica/processoPublicoConsultado.jsp
  sigaex/src/main/webapp/WEB-INF/page/exProcessoConsultaPublica/processoconsultarpublico.jsp
Labels: enhancement, system-properties

#1912 73228* Assinar em substituição com certificado digital
  siga-ex/src/main/java/br/gov/jfrj/itextpdf/Documento.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/ExDocumento.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/ExTipoMovimentacao.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExCompetenciaBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/FuncoesEL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExMobilVO.java
  siga-ex/src/main/resources/db/migration/SIGA_UTF8_V99_0__update_tipo_mov_assinatura_por.sql
  siga-ex/src/main/resources/db/mysql/sigaex/V99.0__update_tipo_mov_assinatura_por.sql
  siga-vraptor-module/src/main/resources/META-INF/tags/cabecalho.tag
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExAssinadorExternoController.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aAssinar.jsp
  sigaex/src/main/webapp/WEB-INF/tags/assinatura_rodape.tag
  sigaex/src/main/webapp/WEB-INF/tld/func.tld
  sigaex/src/main/webapp/imagens/logo_hc.png
  sigaex/src/main/webapp/imagens/logo_prevcom.png
  sigaex/src/main/webapp/public/javascript/assinatura-digital.js
Labels: database

#1283 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  pom.xml
Labels: blocked
