Repository projeto-siga/siga, pull requests merged in 2021-03, with the labels that each got.

#1725 GOVSP1864* - Correções em webservices
  siga-ex/src/main/java/br/gov/jfrj/sigale/ex/vo/ExDocumentoApiVO.java
  siga-ex/src/main/java/br/gov/jfrj/sigale/ex/vo/ExMovimentacaoApiVO.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/DocumentosSiglaArquivoGet.java
  sigaex/src/main/resources/br/gov/jfrj/siga/ex/api/v1/swagger.yaml
Labels: bug

#1731 GOVSP1862* - Webservice gerar protocolo
  siga-base/src/main/java/br/gov/jfrj/siga/base/util/Utils.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/DocumentosSiglaGerarProtocoloPost.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/IExApiV1.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExDocumentoController.java
  sigaex/src/main/resources/br/gov/jfrj/siga/ex/api/v1/swagger.yaml
Labels: enhancement

#1727 PCRJ356 - Correção script CPv102 para preparação da ativação do PIN
  siga-cp/src/main/resources/db/mysql/sigacp/V102.0__configuracao_ativacao_pin.sql
Labels: bug

#1742 PCRJ380 Correção erro no cad. orgaos siga-docker por falta da tabela cp_contrato
  siga-cp/src/main/resources/db/mysql/sigacp/V61_0__cpContrato.sql
Labels: bug, database

#1744 Script V64_0__Configuracoes_para_permitir_exportar_dados.sql não foi encontrado na migration mysql
  siga-cp/src/main/resources/db/mysql/sigacp/V64_0__Configuracoes_para_permitir_exportar_dados.sql
Labels: database

#1756 PCRJ423 - Correção do erro ao acessar a Mesa v.10.0.5.3 - ( siga-docker mysql )
  siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
Labels: bug

#1760 GOVSP1747* - Coluna indicando a posse do documento na mesa virtual 2
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2.java
  siga/src/main/webapp/css/style_siga.css
  siga/src/main/webapp/javascript/mesa2.js
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMesa2Controller.java
  sigaex/src/main/webapp/WEB-INF/page/exMesa2/lista.jsp
Labels: enhancement
