Repository projeto-siga/siga, pull requests merged in 2021-08, with the labels that each got.

#1918 PCRJ_896 melhorar frase de substituto
  siga-cp/src/main/resources/messages_GOVSP.properties
  siga-cp/src/main/resources/messages_PCRJ.properties
  siga-cp/src/main/resources/messages_SIGA.properties
  siga-cp/src/main/resources/messages_TRF2.properties
  siga/src/main/webapp/WEB-INF/page/substituicao/edita.jsp
Labels: system-properties

#1919 PCRJ_675 erro na carga do xml
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/util/SigaCpSinc.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/dao/CpDao.java
  siga-ex-sinc/src/main/java/br/gov/jfrj/siga/ex/sinc/SigaExSinc.java
  siga-sinc-lib/src/main/java/br/gov/jfrj/siga/sinc/lib/OperadorComHistorico.java
  siga-sinc-lib/src/main/java/br/gov/jfrj/siga/sinc/lib/Sincronizador.java
Labels: bug

#1922 GOVSP68801* Prazo para todos assinarem um documento
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/model/enm/CpMarcadorEnum.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V112_0__Marcador_prazo_de_assinatura_expirado.sql
  siga-cp/src/main/resources/db/mysql/sigacp/V112.0__Marcador_prazo_de_assinatura_expirado.sql
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/ExDocumento.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/ExTipoMovimentacao.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExCompetenciaBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExMarcadorBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExDocumentoVO.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExMobilVO.java
  siga-ex/src/main/resources/db/migration/SIGA_UTF8_V101_0__inclusao_tipo_mov_prazo_assinatura.sql
  siga-ex/src/main/resources/db/mysql/sigaex/V101.0__inclusao_tipo_mov_prazo_assinatura.sql
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExDocumentoDTO.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/exibe.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aDefinirPrazoAssinatura.jsp
Labels: enhancement, database

#1928 PCRJ_221 - Assinatura lote não faz juntada automatica
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/model/enm/ExTipoDeConfiguracao.java
Labels: bug
