Repository projeto-siga/siga, pull requests merged in 2022-07, with the labels that each got.

#2121 RM121450 Marcador Resp. pela Assinatura ao invés de Como Subscritor
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/model/enm/CpMarcadorEnum.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/CpMarcador.java
  siga-cp/src/main/resources/messages_GOVSP.properties
  siga-cp/src/main/resources/messages_SIGA.properties
  siga-cp/src/main/resources/messages_TRF2.properties
Labels: bug

#2122 Ajuste na mensagem quando usava o Voltar do Browser
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
Labels: bug

#2124 RM116172 - Correção da Constraint Criada no Script V116
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpBL.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V123_0__Correcao_Constraint_Pessoa_Unica_Ativa.sql
Labels: bug, database

#2128 Rm120826 Refatoramento da funcionalidade de envio do Documento para visualizacao externa
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/logic/ExPodeEnviarParaVisualizacaoExterna.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/notificador/especifico/ExEmail.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/notificador/especifico/ExEnviarEmail.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/notificador/especifico/ExMontarEmail.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/notificador/especifico/ExTemplateEmail.java
  siga-ex/src/main/resources/templates/email/doc-enviado-para-usuario-externo.html
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/enviarParaVisualizacaoExterna.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/resultadoEnvioParaVisualizacaoExterna.jsp
Labels: refactoring

#2131 RM120826 Substituição do JWT pelo CpToken no envio do Documento para visualizacao externa
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpToken.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpBL.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/logic/CpTokenEValido.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V124_0__Token_acesso_externo_ao_documento.sql
  siga-cp/src/main/resources/db/mysql/sigacp/V123.0__token_acesso_externo_ao_documento.sql
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/logic/ExPodeVisualizarExternamente.java
  siga-ex/src/main/resources/templates/email/doc-enviado-para-usuario-externo.html
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/enviarParaVisualizacaoExterna.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/resultadoEnvioParaVisualizacaoExterna.jsp
Labels: refactoring, database

#2129 RM106496 Reuso do método gravarNovaMovimentacao da ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/DocumentosSiglaGerarLinkPublicoPost.java
Labels: refactoring

#2127 PCRJ-2730 Correção serviço anexar arquivo ao documento
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/DocumentosSiglaAnexarPost.java
Labels: bug

#2133 Rm124202 Melhoria visualizacao externa validar url autenticacao
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpBL.java
  siga-cp/src/main/resources/messages_GOVSP.properties
  siga-cp/src/main/resources/messages_SIGA.properties
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/notificador/especifico/ExEmail.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/notificador/especifico/ExEnviarEmail.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/notificador/especifico/ExMontarEmail.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExDocumentoVO.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExMovimentacaoVO.java
  siga-ex/src/main/resources/templates/email/doc-enviado-para-usuario-externo.html
  siga/src/main/java/br/gov/jfrj/siga/api/v1/PinResetPost.java
  siga/src/main/java/br/gov/jfrj/siga/vraptor/UsuarioController.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExAutenticacaoController.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exAutenticacao/autenticar.jsp
Labels: bug, refactoring

#2135 PCRJ-2764 API SIGA documentosGet - inclusao da propriedade limite dias na pesquisa
  siga-base/src/main/java/br/gov/jfrj/siga/base/Prop.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/DocumentosGet.java
Labels: refactoring
