Repository projeto-siga/siga, pull requests merged in 2023-01, with the labels that each got.

#2226 Fearure/govsp/rm147783 refatoramento tramitacao lote
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/AbstractExMovimentacao.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/vo/ExMovimentacaoVO.java
  siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aTransferirLote.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aTransferirLoteGravar.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/listar_docs_transferidos.jsp
Labels: enhancement, refactoring, reestruturacao-organizacional

#2229 RM144211 - Inativação de Lotação em Lote
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpBL.java
  siga/src/main/java/br/gov/jfrj/siga/vraptor/DpLotacaoController.java
  siga/src/main/webapp/WEB-INF/page/dpLotacao/lista.jsp
Labels: reestruturacao-organizacional

#2234 RM142572 - Reestruturação Governo_Inativação Órgão
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpBL.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/dao/CpDao.java
  siga/src/main/java/br/gov/jfrj/siga/vraptor/OrgaoUsuarioController.java
  siga/src/main/webapp/WEB-INF/page/orgaoUsuario/ativarInativar.jsp
  siga/src/main/webapp/WEB-INF/page/orgaoUsuario/historico.jsp
  siga/src/main/webapp/WEB-INF/page/orgaoUsuario/lista.jsp
Labels: reestruturacao-organizacional

#2237 RM148957 - Correção para evitar marcações duplicadas
  sigaex/src/main/webapp/WEB-INF/page/exDocumento/marcar.jsp
Labels: bug

#2233 RM144647 Melhoria Cancelamento Documento
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/logic/ExELotacaoCadastrante.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/logic/ExPodeCancelarDocumento.java
Labels: blocked

#2254 RM150876 Apresentação de erros de documentos não tramitados na tramitação em lote
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exMobil/listar_docs_para_tramitar_lote.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aTramitarLote.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/listar_docs_tramitados.jsp
Labels: enhancement
