Repository projeto-siga/siga, pull requests merged in 2023-02, with the labels that each got.

#2259 GOVSP - RM144279: Tela de pesquisa vinda do quadro quantitativo mostra filtros
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMobilController.java
  sigaex/src/main/webapp/WEB-INF/page/exGadget/execute.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMobil/aListar.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMobil/headerMeses.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMobil/listaSP.jsp
Labels: OnlyGOVSP

#2275 RM126242 - Bloqueio por Tentativa e API de Validação de PIN
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/AbstractCpIdentidade.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpIdentidade.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpBL.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V139_0__contador_tentativa_pin.sql
  siga-cp/src/main/resources/db/mysql/sigacp/V139.0__contador_tentativa_pin.sql
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga/src/main/java/br/gov/jfrj/siga/api/v1/ISigaApiV1.java
  siga/src/main/java/br/gov/jfrj/siga/api/v1/PinValidarPost.java
  siga/src/main/resources/br/gov/jfrj/siga/api/v1/swagger.yaml
Labels: database

#2282 RM151754 - Versionamento de orgão / configurações id inicial do orgão
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/AbstractCpConfiguracao.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpConfiguracao.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/CpConfiguracaoCache.java
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/bl/CpBL.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/AbstractCpOrgaoUsuario.java
  siga-cp/src/main/java/br/gov/jfrj/siga/dp/dao/CpDao.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V141_0__configuracoes_id_orgao_inicial.sql
  siga-vraptor-module/src/main/java/br/gov/jfrj/siga/vraptor/CpConfiguracaoHelper.java
  siga-vraptor-module/src/main/resources/META-INF/tags/cfg-lista-itens.tag
  siga/src/main/java/br/gov/jfrj/siga/vraptor/AcessoController.java
Labels: database

#2285 Permitindo criar documentos sem cadastrante
  siga-cp/src/main/java/br/gov/jfrj/siga/cp/logic/CpEquivaleENaoENulo.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/ExDocumento.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/ExMobil.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/AcessoConsulta.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExAcesso.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExMarcadorBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/ExTramiteBL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/bl/Mesa2Ant.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/logic/ExECadastrante.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/logic/ExPodeAcessarNivel100.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/logic/ExPodeAcessarNivel30.java
  siga-ex/src/main/resources/db/migration/SIGA_UTF8_V116_0__Cadastrante_nulo.sql
  siga-ex/src/main/resources/db/mysql/sigaex/V116.0__Cadastrante_nulo.sql
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/DocumentosPost.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/DocumentosSiglaAssinarAutenticarComSenhaPost.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/ExApiV1Context.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/api/v1/Utils.java
  sigaex/src/main/java/br/gov/jfrj/siga/ex/service/impl/ExServiceImpl.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExAssinadorExternoController.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExDocumentoController.java
Labels: database

#2256 Feature/govsp/143643-integracao-bec-modulo-compra-e-contracao
  siga-base/src/main/java/br/gov/jfrj/siga/base/Prop.java
  siga-cp/src/main/resources/db/migration/CORPORATIVO_UTF8_V136_0__Inclusao_Configuracao_Servico_Para_Ativar_Modulo_Secc.sql
  siga-cp/src/main/resources/db/mysql/sigacp/V136.0__Inclusao_Configuracao_Servico_Para_Ativar_Modulo_Secc.sql
  siga-vraptor-module/src/main/resources/META-INF/tags/menuprincipal.tag
Labels: database, system-properties, blocked

#2295 RM150982 Refatoração para adicionar paginação na tela arquivar em lote
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/AbstractExMovimentacao.java
  siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/FuncoesEL.java
  siga-ex/src/main/java/br/gov/jfrj/siga/hibernate/ExDao.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMobilController.java
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExMovimentacaoController.java
  sigaex/src/main/webapp/WEB-INF/page/exMobil/listar_docs_para_arquivar_corrente_lote.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aArquivarCorrenteLote.jsp
  sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/listar_docs_arquivados_corrente.jsp
  sigaex/src/main/webapp/WEB-INF/tld/func.tld
Labels: enhancement, refactoring, performance

#2299 GOVSP - RM138620 - Erro ao incluir preenchimento automático na reedição de um TMP
  sigaex/src/main/java/br/gov/jfrj/siga/vraptor/ExDocumentoController.java
Labels: bug
